version: "3.9"

services:
  dbserver:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    networks:
      - project_network
  
  backend:
    build: ./backend
    ports:
      - 8080:80
    depends_on:
      - dbserver
    networks:
      - project_network

networks:
  project_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/27
 
volumes:
  postgres_data:
